In [3]:
import numpy as np
import pandas as pd

data = pd.Series(np.random.randn(9),
                index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                       [1, 2, 3, 1, 2, 3, 1, 2, 3]])
data.index.names = ('key1','key2')
data.unstack(level='key1', fill_value=0)

key1         a         b         c         d
key2
1     0.505920 -0.981665 -1.165715  0.000000
2    -0.785989 -0.079065  0.000000  0.825709
3    -1.827188  0.000000 -1.455422 -0.661145

In [ ]:
#將index及欄位移來移去進行樞紐分析
import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(12).reshape((4,3)),
                  index=[['a','a','b','b'],[1, 2, 1, 2]],
                  columns=[['台北','台北','台中'],['Green','Red','Green']])
df.index.names=['key1','key2']
df.columns.names = ['縣市',"顏色"]
df1 = df.stack(level=['縣市','顏色'],future_stack=True)
df1.unstack(level=['key1','縣市','key2'],fill_value=0)
"""
unstack(level=...)
👉 是從 index 拉到 columns
👉 把「直的」變「橫的」

stack(level=...)
👉 是從 columns 壓到 index
👉 把「橫的」變「直的」
"""

key1   a           b
縣市    台北 台中 台北 台中 台北 台中  台北  台中
key2   1  1  2  2  1  1   2   2
顏色
Green  0  2  3  5  6  8   9  11
Red    1  0  4  0  7  0  10   0

In [ ]:
import os
import pandas as pd
current_dir = os.path.dirname(os.path.abspath(__name__))
data_dir = os.path.join(current_dir,'data')
csv_filename = '台鐵車站資訊.csv'
csv_path = os.path.join(data_dir,csv_filename)
station_info = pd.read_csv(csv_path)
csv1_filename = '每日各站進出站人數2020.csv'
csv1_path = os.path.join(data_dir, csv1_filename)
inOut2020_df = pd.read_csv(csv1_path)
inOut2020_merge = pd.merge(inOut2020_df, station_info,how='left',left_on="staCode",right_on="stationCode")
#清理資料
df1 = inOut2020_merge.reindex(columns=['trnOpDate','gateInComingCnt','gateOutGoingCnt','stationName'])
df1.columns = ['日期','進站人數','出站人數','站名']
df1['日期'] = pd.to_datetime(df1['日期'].astype(str))
df2 = df1.set_index('日期')
df2.groupby(by='站名').sum().T #.T 欄列交換

站名,七堵,三坑,三塊厝,三姓橋,三民,三義,三貂嶺,上員,中壢,中洲,...,鳳山,鳳林,鶯歌,鹿野,麟洛,鼓山,龍井,龍泉,龍港,龜山
進站人數,2023475,457042,147363,386310,2748,257824,33705,17338,8722252,138474,...,1717645,125365,2884105,79453,49692,72794,129583,5827,5581,33665
出站人數,2055442,466250,160297,345666,4164,268159,49892,20059,8836667,136042,...,1672513,124964,2898044,76626,53910,75636,126229,6710,7490,32326