In [3]:
import numpy as np
import pandas as pd
df = pd.DataFrame(np.arange(9).reshape((3, 3)), #reshape 做出3欄3列
            index=['a', 'b', 'c'],
            columns=['台北', '台中', '高雄'])
t = df.reindex(index=["b", "c", "a"])
s= t.reindex(columns=['台中', '高雄']) #reindex可以過濾欄或列 重新排序

   台中  高雄
b   4   5
c   7   8
a   1   2

In [6]:
t1 = t.drop(index=["b"])
t1

   台北  台中  高雄
c   6   7   8
a   0   1   2